### ISSUE TITLE
[Bug]: Pushes to Git Desktop, but how do I have that sync automatically with Github?

### ISSUE THREAD

**Issue by ReaderGuy42** [Vinzent03/obsidian-git#128]
### Describe the bug

So it appears that when I use the command "create backup" it pushes to Git Desktop. But do I need to manually push it to Github from there?

Also I'm still getting this error message.

![screen](https://user-images.githubusercontent.com/71895400/139332749-61f687e8-32a5-45f7-840a-4c7a2e4a74a6.png)

Are the two things related?

### Steps to reproduce

"Create Backup" pushes to Desktop. Then manually push to Github.

### Operating system

Linux

**Comment by Giovy27072** [comment]
Hello,I had the same problem and I solved it like this (used on ENDEAVOR OS [ARCH LINUX] ):

1.git config --global credential.helper store
2. I manually did a pull, in my case: git push -u origin main

and I solved it!

i found the solution here:https://stackoverflow.com/questions/35942754/how-can-i-save-username-and-password-in-git

The problem in my case was that git didn't have my credentials, and therefore couldn't pull, and since the credentials (username and password) are in the .gitconfig file (and in my case they weren't there) I searched how to add my credentials to the .gitconfig file and I found the answer at the following link:https://stackoverflow.com/questions/35942754/how-can-i-save-username-and-password-in-git
