### ISSUE TITLE
[Bug]: git not using ssh-agent when run via obsidian-git

### ISSUE THREAD

**Issue by HedgeMage** [Vinzent03/obsidian-git#195]
### Describe the bug

I am running ssh-agent (as provided by openssh-8.6p1) on NixOS 21.05.4719.0fd9ee1aa36 (Okapi), via keychain 2.8.5.  My obsidian version is v0.13.23, and my obsidian-git plugin version is 1.21.1.  My git version is 2.31.1.

Everything works as expected when using git or ssh from the command line, however the obsidian-git plugin prompts me for my key's passphrase every time it takes an action.  It's become quite frustrating, but I'm not sure where the problem lies.

### Steps to reproduce

1. Install keychain and add `eval `keychain -q --confhost --ignore-missing --timeout 720 --eval KEYNAME`
` to your .bashrc
2. Open an interactive terminal and provide your ssh key when prompted
3. Open an Obsidian vault with obsidian-git installed and enabled.
4. Get annoyed at the frequent prompts for ssh password

### Expected Behavior

I should have to enter my ssh password just once every couple of hours, per my keychain configuration.

### Operating system

Linux

**Comment by cyl3x** [comment]
I have the same problem using the ssh agent from KeePass. My guess is that obidian-git is running git in a new environment and therefore the `SSH_AUTH_SOCK` env is missing for git to pick up. :thinking:

**Comment by cyl3x** [comment]
> > I have the same problem using the ssh agent from KeePass. My guess is that obidian-git is running git in a new environment and therefore the `SSH_AUTH_SOCK` env is missing for git to pick up. 🤔
> > EDIT: this seams to be not the case, the env is correctly passed down to simple-git. Also, spawning a child process instead of using simple-git works
> 
> I'm not sure if this means you managed to solve the issue. I'm using a different SSH_AUTH_SOCK and I want obsidian-git to pick it up. Did you manage to figure this out?

I tried to debug this and ended up opening an [issue at simple-git](https://github.com/steveukx/git-js/issues/943). I never found the reason for this behaviour, but using an ssh config instead of the `SSH_AUTH_SOCK` env worked for me.

**Comment by kg4zow** [comment]
You need to make sure that the `SSH_AUTH_SOCK` environment variable, with the correct value, is being "inherited" by Obsidian when it starts.

Most Linux distros take care of this for you automatically, by running `ssh-agent` (or some other program which does the same job and implements the same "Agent API") and exporting the `SSH_AUTH_SOCK` variable during the login process, so that every other process you run during that login session will "inherit" the correct `SSH_AUTH_SOCK` value.

A few things to keep in mind while you're troubleshooting on your own system:

* **Each process has its own environment block.** There is no one single environment block that all processes share.
* The ONLY time a process is able to interact with another process's environment block is when a "parent" process creates a "child" process, the parent *gives* the environment block to the child. Once the child process exists, the parent process can't access the child's environment, any more than it could access any other process's environment.

I know nothing about "NixOS", and I don't recognize the `keychain` command, but what *normally* happens in most Linux distros is ...

(1) Something in the login process runs an `ssh-agent` command. This will *print* lines the necessary lines to set the `SSH_AUTH_SOCK` variable, and possibly a few other variables. For example ...

    $ ssh-agent
    SSH_AUTH_SOCK=/var/folders/8_/3tf1_3_n5tl9q88w7rbh0bnm0000gn/T//ssh-1olfJRykHJ9t/agent.32534; export SSH_AUTH_SOCK;
    SSH_AGENT_PID=32535; export SSH_AGENT_PID;
    echo Agent pid 32535;

(2) An `eval` with backticks or `$(...)` around the `ssh-agent` command, captures this output and "runs" it within the context of the shell where the `eval` command was executed. This means that *that one shell* now has the correct `SSH_AUTH_SOCK` variable. That shell will `export` the variable, so that all child processes created by the shell will also have the variable with the correct value.

(3) When you then start Obsidian *from a  descendant of that shell*, the `SSH_AUTH_SOCK` variable will have the correct value, and Obsidian will be able to use your SSH agent.

The "from a descendant of that shell" part is what seems to cause problems for most people. Usually they don't realize that a hierarchy of "parent" and "child" processes even exist in the first place, or they don't know what the parent/child process hierarchy looks like when starting a process from a shell, from a desktop item, or from an application menu.

Most Linux distros set things up automatically so that `ssh-agent` gets executed very early in the login process, and the `SSH_AUTH_SOCK` variable ends up being inherited by the window manager, which is a parent process of every object you see on the screen - every window, every menu, and even the desktop background itself. This way, any processes started by double-clicking icons would inherit the value. This includes your GUI terminal program, which then passes the variable along to the shells it starts in each window or tab, which then passes it along to every program you run under that shell.

Again, I know nothing about "NixOS", so I don't know if it does this automatically, or if it *can* do this automatically, given how it goes so far out of its way to isolate programs from each other.

Note that macOS does things a *little* bit differently. I'll skip a lot of the details, but suffice it to say that the `SSH_AUTH_SOCK` value *will* be set automatically, and its *value* cannot be changed without disabling SIP (the "high security" mechanism which prevents the OS itself from being modified). The only way to use an agent other than `ssh-agent` is to change what the value *points to*.

On my own systems I do this by replacing the UNIX socket that `launchd` creates when you log in, with a symlink to the socket where `pgp-agent` is listening for SSH connections. This allows me to use `pgp-agent` _as_ my SSH agent, which then allows me to store my SSH secret keys on a [YubiKey](https://yubico.com/) device. This works with almost every SSH client, including `ssh`, `scp`, `sftp`, `git`, BBEdit, and Obsidian with the obsidian-git plugin. And with the right `git` configuration, all of my commits are PGP-signed, with the PGP secret keys also stored on the same YubiKey.

As a final note ... there are some poorly written SSH client programs out there which just plain don't *know* how to talk to an agent at all. **The `obsidian-git` plugin DOES know how to talk to an SSH agent.** I know this because I do it all the time, with Github repos *and* with two different private repo servers (one using [Gitea](https://about.gitea.com/products/gitea/), the other using [Gitolite](https://gitolite.com/)).

**Comment by Vinzent03** [comment]
@kg4zow Thanks for your great detailed explanation. It's how I understand the topic as well. It's really hard to create a correct guide as the circumstances are always so different. I'm closing this, as the plugin itself doesn't handle the authentication, but needs the correct environment variables and setup to delegate it to the git cli, which handles that much better.
