### ISSUE TITLE
[Bug]: "fatal: Could not read Username: Device Not Configured"

### ISSUE THREAD

**Issue by mutachre** [Vinzent03/obsidian-git#254]
### Describe the bug

I'm getting the error "fatal: Could not read Username for 'https://www.github.com/': Device Not Configured" everytime Obsidian tries to push. I'm running on OS X Monterey 12.1 / Apple M1.
Any idea how to solve?

<img width="337" alt="Schermata 2022-07-01 alle 13 52 28" src="https://user-images.githubusercontent.com/62408551/176977888-7539fb0c-607d-4d3f-93e1-97bf12467596.png">

### Steps to reproduce

Auto or manual commit.

### Operating system

macOS

### Plugin version

1.26.1

**Comment by peterkaminski** [comment]
In my experience, this isn't an Obsidian Git problem, it just means authentication isn't set up.

There are two paths forward:

1. If you use Git from the command-line or another app, and you have a GitHub SSH key set up, you need to [switch your remote URL from HTTPS to SSH](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#switching-remote-urls-from-https-to-ssh).
2. Otherwise, you need to cache your Git credentials. I haven't done this, but I can include some links to pages that might help below (no guarantees).

- [How to Set Up HTTPS Personal Access Tokens for Github Authentication](https://www.howtogeek.com/devops/how-to-set-up-https-personal-access-tokens-for-github-authentication/)
-  [Caching your GitHub credentials in Git - GitHub Docs](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git)
- [Updating credentials from the macOS Keychain - GitHub Docs](https://docs.github.com/en/get-started/getting-started-with-git/updating-credentials-from-the-macos-keychain)
- [Creating a personal access token - GitHub Docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
- [Git - Credential Storage](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) (note, refers to "Git Credential Manager for Windows"; however, "Warning: Older versions of Git for Windows came with Git Credential Manager for Windows. This older product is no longer supported and cannot connect to GitHub via OAuth. We recommend you upgrade to the [latest version of Git for Windows](https://github.com/git-for-windows/git/releases).")

**Comment by mutachre** [comment]
Thank you. Apparently it seems to be solved by switching from https to ssh, probably the issue was triggered by 2FA. 
This is my first time using an ssh key, I will try to test it some more.

**Comment by Vyeche** [comment]
Interesting, I got it close. I used the first link on switching to SSH.

I followed: 
- [SSH New Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

```
Uncaught (in promise) Error: ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by wenlzhang** [comment]
> 1. If you use Git from the command-line or another app, and you have a GitHub SSH key set up, you need to [switch your remote URL from HTTPS to SSH](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#switching-remote-urls-from-https-to-ssh).

This worked for me.

**Comment by Vyeche** [comment]
> In my experience, this isn't an Obsidian Git problem, it just means authentication isn't set up.
> 
> There are two paths forward:
> 
> 1. If you use Git from the command-line or another app, and you have a GitHub SSH key set up, you need to [switch your remote URL from HTTPS to SSH](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#switching-remote-urls-from-https-to-ssh).
> 2. Otherwise, you need to cache your Git credentials. I haven't done this, but I can include some links to pages that might help below (no guarantees).
> 
> * [How to Set Up HTTPS Personal Access Tokens for Github Authentication](https://www.howtogeek.com/devops/how-to-set-up-https-personal-access-tokens-for-github-authentication/)
> * [Caching your GitHub credentials in Git - GitHub Docs](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git)
> * [Updating credentials from the macOS Keychain - GitHub Docs](https://docs.github.com/en/get-started/getting-started-with-git/updating-credentials-from-the-macos-keychain)
> * [Creating a personal access token - GitHub Docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
> * [Git - Credential Storage](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) (note, refers to "Git Credential Manager for Windows"; however, "Warning: Older versions of Git for Windows came with Git Credential Manager for Windows. This older product is no longer supported and cannot connect to GitHub via OAuth. We recommend you upgrade to the [latest version of Git for Windows](https://github.com/git-for-windows/git/releases).")

Solved my issue: [Caching your GitHub credentials in Git - GitHub Docs](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git)

**Comment by abrahamp47** [comment]
> Interesting, I got it close. I used the first link on switching to SSH.
> 
> I followed:
> 
> * [SSH New Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
> * https://askubuntu.com/questions/1196164/ssh-askpass-exec-usr-libexec-openssh-ssh-askpass-no-such-file-or-directory-e
> 
> ```
> Uncaught (in promise) Error: ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> After I install SSH_ASKPass. I'm getting a prompt.
> 
> I may have messed up this step.
> 
> ```
> sh-keyscan -t rsa github.org >> ~/.ssh
> ```
> 
> The example that was given:
> 
> ```
>         ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
> ```
> 
> ![Screenshot 2022-08-28 9 03 11 PM](https://user-images.githubusercontent.com/972377/187103592-fe89e9c1-af79-4434-acc5-8b7417e0ac79.png)
> 
> ```
> plugin:obsidian-git:10399 Uncaught (in promise) Error: Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

Hey , 
Just add this in your ssh config file -

Host github.com
  StrictHostKeyChecking no
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519

**Comment by gjtiquia** [comment]
using ssh key helped fix the problem for me running Obsidian in Ubuntu thanks!
