### ISSUE TITLE
[Bug]: Setting up Obsidian Git on a new machine, trouble with "Please make sure you have the correct access rights and the repository exists."

### ISSUE THREAD

**Issue by ReaderGuy42** [Vinzent03/obsidian-git#346]
### Describe the bug

I try this `git push -u origin main` and get the error below. I'm trying to sync a second machine to my repo.

I've added a new SSH key to my new machine and github (I think that worked) but can't figure out what to do now.

This isn't technically in the plugin yet, since I haven't been able to get that far. Can you still help me with this?

### Relevant errors (if available)

```shell
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
 git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Steps to reproduce

Try pushing to remote. Get error

### Operating system

Linux

### Plugin version

2.8.0

**Comment by architchandra** [comment]
I'm facing the same issue. I copied over the vault (including the Git directory) onto the new machine and set up a new SSH on it. Since then, I have been able to manually push to the remote repo using the command line but always see this error when trying to push through the plugin.

**Comment by Vinzent03** [comment]
@architchandra Do you have to enter a passphrase on the command line for the ssh key?

**Comment by architchandra** [comment]
Hi @Vinzent03 

I'm not sure what clicked but I'm no longer facing this issue.

I'm using a Mac and the SSH key that I created was not getting loaded into the SSH agent automatically upon login, even after adding details to a config file. So, I added a command to load the key into the agent into my .zshenv file using `ssh-add --apple-load-keychain` (so that application-generated commands also have access to the passphrase).

Since then I have been able to work seamlessly despite my SSH key having a passphrase. And to answer your original question, I had to enter the passphrase the first time I added my key into the SSH agent but not after that.

**Comment by chaosraine** [comment]
> 

Dude I'm like 2 full days with this exact problem and you may have just solved it for me.
I knew it must have to do with Obsidian git having access to the passphrase but I could not for the life of me figure out what to do about it (despite other people clearly struggling with it)

Now I'm gonna go see if I can break it again, but it's fixed for now! Many thanks!!

**Comment by chaosraine** [comment]
Okay, I DID break it (I ran --apple-load-keychain from the terminal instead of adding it to the bash profile so it broke on login as expected)

But I think I figured out where it was broken in the first place. I followed the GitHub guide for setting up the SSH keys and part of that included adding it to the keychain in the config file. They suggested:

> Host *.github.com
>   AddKeysToAgent yes
>   UseKeychain yes
>   IdentityFile ~/.ssh/id_ed25519

I didn't have any clue if it would work, but I figured that if the problem was with obsidian-git not being able to pull from the keychain, maybe I needed to change the host. At first, I changed host to * which did work, but I wasn't sure why I couldn't include GitHub. So I made the host just *github.com (removing the . dot after the *) and now it seems to be working in Obsidian even without loading the keychain through the bash profile/zshenv (which also did work)

It was literally one dot. I'm not okay 😮‍💨

Since probably a lot of us noobs are using the GitHub guide for setup, I'd guess a lot of the publickey errors are coming from that one dot. Now I'm going to go sleep for two days straight and then work on fixing the iPad side of things that I surely broke in the process of getting this one working haha

**Comment by elvisisvan** [comment]
> > Host *.github.com
> > AddKeysToAgent yes
> > UseKeychain yes
> > IdentityFile ~/.ssh/id_ed25519
> At first, I changed host to * which did work, but I wasn't sure why I couldn't include GitHub. So I made the host just *github.com (removing the . dot after the *)

im trying to clone my private repo using `Obsidian Git: Clone an existing remote repo` option then i got this same error too
![image](https://github.com/denolehov/obsidian-git/assets/69122770/78077157-b18b-406f-be83-6807965a5382)

@chaosraine where exactly did you find this 4-line config?

**Comment by chaosraine** [comment]
> Reference
This is the guide I was using, if I'm remembering correctly
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

The file was my .ssh/config file. You can create it using the instructions on that page (on macos). It is blank upon creation, so I pasted in the recommended example code from the github guide. 

The only real problem I ran into was that it recommended using Host: *.github.com - I changed it to *github.com (without the first dot) and that's what worked!

**Comment by architchandra** [comment]
@chaosraine - This config is from Github's [docs related to creating SSH keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent).

From what I can remember, the given config mentioned `*.github.com` in the past, which is where most of us ran into trouble. Github itself seems to have changed it to just `github.com` in the docs now and that seems to work fine for me. Some remnants of the previous config still seem to remain eg. in the note right below the config.

![Screenshot 2023-08-20 at 10 27 45 AM](https://github.com/denolehov/obsidian-git/assets/8830075/bb320c7e-825a-4fad-9644-f25c9ac5dcf7)

**Comment by jsco2t** [comment]
Just wanted to report that the fix from @architchandra also solved this issue for me. I mistakenly had `*.gitlab.com` as the host in my config. Changing that to `*gitlab.com` resolved this issue. It's a strange issue as I would expect either to work - and the `*.gitlab.com` would be the one I would prefer as it should be more specific about where the key can be used.

In any case - thank you for posting your fix.
