### ISSUE TITLE
Authentication issue with ssh passphrase

### ISSUE THREAD

**Issue by evanaze** [Vinzent03/obsidian-git#42]
Hi,

I am getting the error message:
<img width="294" alt="Screen Shot 2021-01-23 at 9 43 00 AM" src="https://user-images.githubusercontent.com/25772568/105609650-93548c00-5d5f-11eb-8356-3b823b37e69f.png">

#### About my setup:
I have `obsidian-git` running on both my Mac and an Arch Linux install. It works great on Arch Linux, but I get the above error message on Mac whenever I start Obsidian. I use SSH to pull from Git, and I have two different SSH keys on my two machines. The key on my Arch Linux machine is not password protected, and my Mac's is. They are both added to `ssh-agent` and I have no problems pulling or pushing to git outside of this on either machine.

Happy to provide any more info. I checked the Issues and could not find any similar to mine. Thank you.

**Comment by icaroo** [comment]
Same here, but Windows user.
I'm using gitbash, works ok by command line.

**Comment by s-kyy** [comment]
Same issue on my end with Windows, I only have one ssh key linked to github, so maybe it needs to save the ssh password?

**Comment by Vinzent03** [comment]
When you use your ssh key, you have to type in your ssh-key password right?

**Comment by s-kyy** [comment]
@Vinzent03 Whenever I open git bash, I:
1) start the ssh-agent
2) ssh-add the relevant keys + you get prompted for a password to type in here
3) Do the usual git pull/add . / commit / push steps

I think if you don't add the ssh keys, then you get prompted for the password each time. Personally, I adjusted my ~/.bashrc file so that every time I open a git bash terminal I add my ssh keys + pw's at the beginning.

**Comment by Vinzent03** [comment]
The problem is the passphrase . Will take a look how to solve this.

**Comment by Vinzent03** [comment]
When you use the default terminal and start the ssh-agent and run `ssh-add`. And type in your passphrase. Does the issue still persist? I can't help more, because I am on Linux.

**Comment by s-kyy** [comment]
Using the git bash terminal, entering ssh-add and leaving it open while I run a git pull from Obsidian, I get the same error: 
![image](https://user-images.githubusercontent.com/19920083/111369698-c0416300-866d-11eb-816b-47b4e9234374.png)

I haven't set it up using the Windows command terminal before, but maybe this link would help? https://stackoverflow.com/a/40720527

**Comment by Vinzent03** [comment]
Well you have to tell me if this works. That has nothing to do with this plugin.

**Comment by MikeTuomas** [comment]
Running `ssh-add` resolved this for me. I am using macOS 11.3.1

**Comment by ZerkerEOD** [comment]
@s-kyy, sorry I know this is closed but wondering what you did to prevent being asked every time rather than the first time when opening the terminal. Is there a way to check if the key has already been added?

**Comment by s-kyy** [comment]
@ZerkerEOD 
Assuming you use Windows, and that you already setup your ssh keys I have two files in my `~/` user folder:

`~/.bash_profile`
```
# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
```

`~/.bashrc` (or `~/.profile`):
```
eval `ssh-agent`
ssh-add 
```

Then in the `~/.ssh/config` file:
```
Host github.com #custom name for the host
  HostName ssh.github.com #or other website directing to the host
  User git #usually your username, but github ssh takes git as the username
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/id_rsa #add your ssh-key file path

AddKeysToAgent yes
```

It's been a while since I modified this setup, but I think this is all you need. This would prompt a password (if there is one) for your ssh keys that you're adding every time you open git bash (linked to Git for Windows). 

Hope it works for you.

**Comment by bramuccci** [comment]
I ended up removing the passphrase. I know is not a good solution, but is a simple one.
`ssh-keygent -p`

**Comment by cybersholt** [comment]
Depending on your setup with Windows 10 you may need to add this via an elevated console, only if you're using **OpenSSH for Windows**

`git config --global core.sshCommand C:/Windows/System32/OpenSSH/ssh.exe`

**Comment by veggie-garden** [comment]
`ssh-add` also works in windows! I followed what exactly written [over here](https://stackoverflow.com/questions/18683092/how-to-run-ssh-add-on-windows/40720527#40720527).

**Comment by Kabobi** [comment]
I solved this problem by setting the default SSH user, in the `~/.ssh/config` file:
```config
 Host *
    User your_default_ssh_user
    IdentityFile ~/.ssh/your_default_ssh_key
```

**Comment by NurgisaA** [comment]
i am using manjaro  and ssh-askpass not defined, but system used ksshaskpass. Im trying use alias, but this dont work. How to fix it.

**Comment by jlyonsmith** [comment]
I'm on macOS.  For me the problem was two-fold:

1. I'm using ECC keys with a passphrase
2. I'm using the keychain and `ssh-add` to cache passwords

Adding the following to your `~/.ssh/config` should fix things:

```conf
# Github
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
  User git
```

The use `ssh-add ~/.ssh/id_ed25519 --apple-use-keychain` to add your passphrase to the keychain one time and you'll be golden.

**Comment by nate-griff** [comment]
Quick fix for Windows users. Worked for me on Windows 11:
``` powershell
Set-Service -Name 'ssh-agent' -StartupType Automatic
Start-Service ssh-agent
```
Then make sure to use 
```
AddKeysToAgent yes
```
in your ssh config either for the specific host or all hosts.

If you still run into issues, it's probably with git itself. Make sure you change the ssh agent:
```powershell
git config --global core.sshCommand "'C:\\Windows\\System32\\OpenSSH\\ssh.exe'"
```
