### ISSUE TITLE
Still, can't get obsidian to work with git gpg signing

### ISSUE THREAD

**Issue by lnxfsf** [Vinzent03/obsidian-git#641]
I still can't get obsidian to work with git gpg signing, it says:

Error I get is:
```
git obsidian error: error: gpg failed to sign the data:
[GNUPG:] KEY_CONSIDERED xxxxxxxxxxxxxxxxxxxxxxxx 2
[GNUPG:] BEGIN_SIGNING H8
gpg: signing failed: No pinentry
[GNUPG:] FAILURE sign xxxxxxxx
gpg: signing failed: No pinentry

fatal: failed to write commit object


```

<br/>
<br/>

```
# .gitconfig

[gpg]
	program = /usr/bin/gpg
[commit]
	gpgsign = true

```

I checked this, but still doesn't solve issue:
- https://github.com/denolehov/obsidian-git/issues/21

**Comment by fleveillee** [comment]
**This might be considered a workaround,** but I was able to do it this way: I switched my repository to use ssh instead of HTTPS and used an ssh GPG key with no passphrase. This way, Obsidian does not need to handle the signing process, as it is now handled indirectly through an ssh commit.

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by Vinzent03** [comment]
The original issue may be solved now with a recent update, so I'm going to close this. If you still encounter this, please comment or open a new issue.

**Comment by madsmh** [comment]
I am still encountering this issue.

**Comment by courier83** [comment]
On macosX, 

`.config` obsidian file:

[gpg]
program = /usr/local/bin/gpg
[commit]
gpgsign = true

In a term: :

`git config --global user.signingkey YOUR_ID  `

`git config --global commit.gpgSign true`

A commit-&-sync later, Obsidian (with Gpgtools) asked me for the pass and it rocks !

**Comment by dominics** [comment]
I think this can also happen if you don't have a GUI-friendly pinentry program (I'd usually enter my gpg key password at the CLI). In that case, where Obsidian fails to show the stdin/stdout pinentry, my error looked like:

```
error: gpg failed to sign the data
fatal: failed to write commit object
```

It looks like there's no real alternative to installing a GUI pinentry (which is a bit annoying as my .gnupg config is synced to non-mac machines), and doing so fixes the issue:

```shell
brew install pinentry-mac
echo "pinentry-program $(brew --prefix)/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
killall gpg-agent
```

I'd wager this was the original problem OP was having (because they got a "No pinentry" error), even though I get a slightly less-verbose error in the same situation.

**Comment by madsmh** [comment]
> I am still encountering this issue.

I am running Fedora 42, I get

```No keybox daemon running```

But if I manually commit/push, then Obsidian Git seems to work with no issue.

**Comment by keremimo** [comment]
If you are still having this issue, run this command to add this to your git configuration, replace <PATH_TO_YOUR_GPG> with the output you get from `which gpg`:

git config --global gpg.program <PATH_TO_YOUR_GPG>

**Comment by nv6** [comment]
> If you are still having this issue, run this command to add this to your git configuration, replace <PATH_TO_YOUR_GPG> with the output you get from `which gpg`:
> 
> git config --global gpg.program <PATH_TO_YOUR_GPG>

This worked for me on macOS! For some reason GnuPG installed from Homebrew wasn't being picked up automatically. I just ran `git config --global gpg.program $(which gpg)`, evaluating to `/opt/homebrew/bin/gpg` from `$PATH`.
