### ISSUE TITLE
[Bug]: Command to easily backup files is gone

### ISSUE THREAD

**Issue by sirlaughalot90** [Vinzent03/obsidian-git#774]
### Describe the bug

I updated to Git plugin to 2.27.0 and now the 'Create Backup' command is gone (I think this is what it was called...). It was a fast way to combine commit/push into a single command and removing it seems as a regression.

### Steps to reproduce

-

### Operating system

macOS

### Installation Method

None

### Plugin version

2.27.0

**Comment by Vinzent03** [comment]
I have changed the backup phrase to "Commit-and-sync", because it describes what happens more precisely. Backup means storing a copy somewhere and leaving the local state as it is, but by pulling, you actually change your local version as well.
Everything should work like before, except the name is changed.

**Comment by sirlaughalot90** [comment]
Ah, thank you for your quick reply and the clarification. There is still a peculiarity in conjunction with the Better Command Palette plugin: When filtering for "commit and..." it only shows "Commit-and-sync and then close Obsidian" which caused my confusion in the first place. Any idea why this is happening and how to circumvent it? Thank you.

**Comment by Vinzent03** [comment]
I can reproduce the issue with the Better command palette plugin, but thats an issue with that plugin, because the search is not actually fuzzy finding. To still use that plugin you have to search for "Commit-"
