### ISSUE TITLE
[Bug]: commit-and-sync doesn't pull when there is no files to commit

### ISSUE THREAD

**Issue by juliano-araujo** [Vinzent03/obsidian-git#787]
### Describe the bug

This occurs when I run the commit-and-sync with the pull enabled. When there is changes to commit all goes all, but for me it seems that when there is no new changes to push the pulling part of the operation is aborted

### Steps to reproduce

1. Make changes in the repository (via another Obsidian instance or via file)
2. Go to Obsidian and do the commit-and-sync action

### Expected Behavior

Even that there is nothing to commit, the sync part of the command should occur anyways

### Operating system

Windows

### Installation Method

None

### Plugin version

2.27.0

**Comment by Vinzent03** [comment]
Not pulling, when no commit happened, was the expected behavior. It suited the previous phrasing "Backup", but for the new phrasing "commit-and-sync" I think you are right. So it now tries to pull on commit-and-sync as well. Though, just to mention it, there is and was the extra interval for pulling as well.

**Comment by Vinzent03** [comment]
@dkbarn Thanks for the info!
This is now released in 2.28.0 :tada:
